### ISSUE TITLE
any plan to support multi branch release such as beta / 1.x?

### ISSUE THREAD

**Issue by atian25** [semrel-extra/zx-semrel#10]
## Issue type
* [ ] bug report
* [ ] idea
* [x] question
* [ ] other

## Actual behavior

* [ ] I've read the docs. This case is not mentioned
* [ ] Similar issue does not exist

## Specifications

- version:
- platform:
- ci:

**Comment by atian25** [comment]
```bash
git tag -l 'v*' --sort=-v:refname --merged `git branch --show-current`
```

**Comment by antongolub** [comment]
Perhaps. This is just a snippet, so everyone can change it as they wish.
